<?xml version="1.0" encoding="UTF-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

	<!-- battery block -->
	<link name="battery_block_link">
		<inertial>
			<!-- from Solid Edge "Battery Block V2 - 22Ah - 24V.asm" -->
			<origin xyz="-0.09568 0 0.00658" />
			<mass value="2.401" />
			<inertia ixx="0.002" iyy="-0.001" izz="-0.001" ixy="0" ixz="0" iyz="0" />
		</inertial>
		<visual>
			<geometry>
				<mesh filename="package://earth_rover_description/meshes/battery_block.dae" />
			</geometry>
		</visual>
	</link>

	<gazebo reference="battery_block_link">
		<selfCollide>false</selfCollide>
	</gazebo>

	<joint name="battery_block_joint" type="fixed">
		<parent link="front_base_link" />
		<child link="battery_block_link" />
		<origin xyz="${base_x/2} 0 0" />
	</joint>

</robot>