<?xml version="1.0" encoding="UTF-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="00-ankles_properties.xacro" />

    <xacro:macro name="ankle" params="name parent reflect reflect_y">

		<link name="${name}_ankle">
			<inertial>
				<!-- from Solid Edge "Steering Block.asm" -->
				<origin xyz="0 ${reflect*(-wheel_offset_y + 0.02493)} ${wheel_offset_z + 0.05588}" />
				<mass value="0.271" />
				<inertia ixx="0.01" iyy="0.01" izz="0.01" ixy="0" ixz="0" iyz="0" />
			</inertial>
			<visual>
				<origin xyz="0 ${reflect*wheel_offset_y} ${wheel_offset_z}" rpy="0 0 ${M_PI if reflect == -1 else 0}"/>
				<geometry>
					<mesh filename="package://earth_rover_description/meshes/steering_block.dae" />
				</geometry>
				<material name="silver"/>
			</visual>
			<collision>
				<origin xyz="0 0 ${ankle_offset_z}" />
				<geometry>
					<cylinder radius="0.016" length=".18"/>
				</geometry>
			</collision>
		</link>

		<gazebo reference="${name}_ankle">
			<selfCollide>false</selfCollide>
		</gazebo>

		<!-- Ankle Transmission & Joints -->
		<joint name="${name}_ankle_joint" type="revolute">
			<parent link="${parent}" />
			<child link="${name}_ankle" />
			<axis xyz="0 0 1" />
			<origin xyz="${reflect_y*ankle_offset_x} ${reflect*ankle_offset_y} -${ankle_offset_z}" />
			<limit lower="-${angle_limit_ccw}" upper="${angle_limit_cw}" effort="7" velocity="15" /> <!-- guesses -->
		</joint>

		<transmission name="${name}_ankle_transmission">
			<type>transmission_interface/SimpleTransmission</type>
			<actuator name="${name}_ankle_motor" />
			<joint name="${name}_ankle_joint">
				<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
			</joint>
		</transmission>
    
    </xacro:macro>
</robot>